---
title: "Kan man köpa kunskap?"
author: "Martin Sjöborg"
date: "2020-12-17"
output:
  ioslides_presentation:
    logo: SU_logo_CMYK.png
    incremental: TRUE
    css: slides.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(knitr.table.format = "html")
options(digits = 2)
library(tidyverse)
library(sf)
library(httr)
library(jsonlite)
library(ggspatial)
library(readxl)
library(corrplot)
library(cluster)
library(gridExtra)
library(modelr)
library(kableExtra)
library(pxweb)
library(dendextend)
library(viridis)
library(gganimate)


get_merit <- function(year){
  start_year <- sprintf("%02d", as.numeric(year)) # Add leading zero to single digit years.
  end_year <- as.numeric(year) + 1
  end_year <- sprintf("%02d", as.numeric(end_year)) # Add leading zero to single digit years.
  file <- paste0("../Data/exp_slutbetyg_kommun_20",start_year,"_",end_year,".csv")
  ifelse(as.numeric(end_year) > 15, skip_row <- 6, skip_row <- 5)
  slutbetyg <- read_csv2(file, skip = skip_row, col_names = TRUE)
  
  slutbetyg <- slutbetyg[,-length(slutbetyg)] %>% #Strip last empty column
    filter(`Typ av huvudman` == "Kommunal") %>% # Bara kommunala huvudmän
    select(2,9) %>% 
    mutate_all(funs(str_replace(.,",", "."))) 
  
  colnames(slutbetyg) <- c("municipality", "merit")
  slutbetyg$period = as.numeric(paste0("20",end_year))
  
  return(slutbetyg)
}

betyg <- map_df(8:17, function(year) {
  mat <- suppressWarnings({suppressMessages({get_merit(year)})})
})

betyg$merit <-
  if_else(betyg$period > 2014, 
          (16 / 17 * as.numeric(betyg$merit)),
          (as.numeric(betyg$merit))
  ) # Correct for grade reform in 2015


inflation <- read_excel("../Data/pr0101_2018a01_di_06-07_sv.xls",
                        sheet = 3,
                        range = "A180:B197")
colnames(inflation) <- c("period","inflation")

kommundata <- read_csv2("../Data/Kommungruppsindelning_2017.csv") %>% 
  select(`Kommun namn`, Kommunkod, "Kommungrupp 2017 namn") %>% 
  rename(municipality = Kommunkod) %>% 
  rename(typ = "Kommungrupp 2017 namn") %>% 
  mutate(typ = replace(typ, typ %in% c("Pendlingskommun nära större stad","Lågpendlingskommun nära större stad"), "Pendling större stad")) %>% 
  mutate(typ = replace(typ, typ == "Pendlingskommun nära storstad", "Pendling storstad")) %>% 
  mutate(typ = replace(typ, typ %in% c("Landsbygdskommun","Landsbygdskommun med besöksnäring"), "Landsbygd")) %>%
  mutate(typ = replace(typ, typ %in% c("Pendlingskommun nära större stad","Lågpendlingskommun nära större stad"), "Pendling större stad")) %>% 
  mutate(typ = replace(typ, typ == "Pendlingskommun nära mindre stad/tätort", "Mindre stad/tätort"))
  



pisa_result <- map_df(1:3, function(sheet_number) {
  test <- read_xls("../Data/IDEExcelExport-Jan072020-0427PM.xls",
                   sheet = sheet_number,
                   range = "B12:D16"
                   )
  }) %>% 
  group_by(`Year/Study`) %>% 
  summarize(
    pisa = mean(Average)
    )

interpolated_pisa <- data.frame(period = approx(x = pisa_result$`Year/Study`,
                                                y = pisa_result$pisa, n = 2018-2009+1)$x,
                                pisa = approx(x = pisa_result$`Year/Study`,
                                              y = pisa_result$pisa, n = 2018-2009+1)$y
                                )




gammal_skolskjuts <- pxweb_get_data("http://api.scb.se/OV0104/v1/doris/sv/ssd/START/OE/OE0107/OE0107G/FskolKlass", 
                      list(ContentsCode = "OE0107A2", 
                           Region = "*", 
                           Nyckeltal = c("375","435","450"), 
                           Tid = c("2009","2010","2011","2012"))) %>%
  spread(key = uppgift, value = "Nyckeltal för kommunernas förskoleklass, grundskola och obl. särskola") %>% 
  rename("period" = år) %>% 
  left_join(kommundata, by = c("region" = "Kommun namn")) %>%
  mutate(kostnad = `grundskolan, kostnad totalt (tkr)` * 1000 /
          `grundskolan, genomsnittligt antal elever folkbokförda i kommunen` -
          `grundskolan, kostnad per elev för skolskjuts (kr)`
         ) %>% 
    select(municipality, period, kostnad) %>% 
  mutate(period = as.numeric(as.character(period)))




get_kolada <- function(kpi, years){
  years_and_kpi <- expand.grid(kpi,years)
  urls <- paste0("https://api.kolada.se/v2/data/kpi/", years_and_kpi[[1]], "/year/", years_and_kpi[[2]])
  bruttokostnad <- data.frame("municipality" = as.character()
                              ,"kpi" = as.character()
                              ,"period" = as.character() 
                              ,"value" = as.character()
  )
  
  for (url in urls) {
    bruttokostnad_json <- GET(url) %>%
      content("text")
    
    if (!grepl("<",bruttokostnad_json)){ #If not bad requests (400)
      
      
      bruttokostnad_old <-  bruttokostnad
      if (length(bruttokostnad) != 0) { # 
        bruttokostnad <- head(fromJSON(bruttokostnad_json)$values, 290)
        bruttokostnad <- rbind(bruttokostnad,bruttokostnad_old)
      }}}
  return(unnest(bruttokostnad) %>% 
           filter(gender == "T") %>%  # both genders
           select(-count,-gender,-status))}

kpi <-  c("N15006","N15033","U15015")
years <- seq(2009,2018)

kolada <- get_kolada(kpi,years) %>% 
  spread(key = kpi, value = value) %>% 
  rename(elevdensitet = N15033) %>% 
  rename(kostnad = N15006) %>% 
  rename(skolskjuts = U15015) %>%
  mutate(kostnad = as.numeric(kostnad) - as.numeric(skolskjuts)) %>% 
  select(-skolskjuts)



data <- kolada %>% 
  left_join(gammal_skolskjuts, by = c("period","municipality")) %>%
  left_join(betyg, by = c("period","municipality")) %>%
  mutate(kostnad = coalesce(kostnad.x,kostnad.y) / 1000) %>% 
  select(-kostnad.x,-kostnad.y) %>% #Skräp från sammanslagningen
  left_join(interpolated_pisa, by = "period") %>% # Joina Pisa
  left_join(kommundata, by = "municipality") %>% #Joina kommuntyper
  left_join(inflation, by = "period") %>%  #Joina inflationsdata
  mutate(kostnad = kostnad * (100 + inflation) / 100.0) %>% #Inflationsjustering
  select(-inflation) %>% #Bort med inflation
  mutate(merit = as.numeric(merit)) %>% 
  na.omit


grouped_year_data <- data %>% 
  group_by(period,typ) %>% 
  summarise(
    elevdensitet = mean(elevdensitet),
    kostnad = mean(kostnad),
    merit = mean(as.numeric(merit)),
    pisa = mean(pisa)
  )

grouped_muni_data <- data %>% 
  group_by(municipality) %>% 
  summarise(
    elevdensitet = mean(elevdensitet),
    kostnad = mean(kostnad),
    merit = mean(as.numeric(merit)),
    pisa = mean(pisa)
  )

grouped_typ_data <- data %>% 
  group_by(typ) %>% 
  summarise(
    elevdensitet = mean(elevdensitet),
    kostnad = mean(kostnad),
    merit = mean(as.numeric(merit))
  )
```
## Grafer från rådata
```{r,INFL,echo=FALSE, results = FALSE}
p <- ggplot(grouped_year_data, aes(x = period)) +
  theme_bw() +
  theme(axis.text.x=element_text(angle = -45, hjust = 0)) +
  xlab("")

kostnad_period <- p + 
        geom_point(aes(y = kostnad, color = typ)) +
  scale_color_viridis(discrete=TRUE) 

pisa_period <- p + 
        geom_point(aes(y = pisa, color = merit)) +
  scale_color_viridis(discrete=FALSE)

elev_period <- p + 
        geom_line(aes(y = elevdensitet, color = typ)) +
  scale_color_viridis(discrete=TRUE)

merit_period <- p + 
        geom_line(aes(y = merit, color = typ)) +
  scale_color_viridis(discrete=TRUE)

grid.arrange(kostnad_period, pisa_period, 
                 elev_period, merit_period,
                 ncol = 2, nrow = 2,
                 top = "Titel", widths = c(5,5)) 
```

## Kommuntyper
```{r,echo=FALSE, results = FALSE}
ggplot(grouped_year_data, 
  aes(x = elevdensitet, y=merit, size = kostnad, colour = typ)) +
  geom_point(show.legend = TRUE, alpha = 0.7) +
  scale_color_viridis_d() +
  scale_size(range = c(2, 12)) +
  labs(x = "Elevdensitet", y = "Meritvärde")

p <- ggplot(
  grouped_year_data, 
  aes(x = elevdensitet, y=merit, size = kostnad, colour = typ)) +
  geom_point(show.legend = TRUE, alpha = 0.7) +
  scale_color_viridis_d() +
  scale_size(range = c(2, 12)) +
  labs(x = "Elevdensitet", y = "Meritvärde") +
  transition_time(period) +
  labs(title = "Year: {as.integer(frame_time)}") +
  shadow_mark(alpha = 0.5, size = 6)
```


## Klustring
```{r,echo=FALSE, results = FALSE}
library(cluster)
library(fpc)
grouped_mat <- as.matrix(grouped_typ_data[,c(-1)]) # Ta bort textkolumn
  rownames(grouped_mat) <- grouped_typ_data$typ
  
cls <- kmeans(grouped_mat, centers = 4)
cluster_data <- grouped_year_data
cluster_data$cluster <- cls$cluster

ggplot(cluster_data, aes(y = merit, x=kostnad, size = cluster, colour = typ)) +
  geom_point(show.legend = TRUE, alpha = 0.7) +
  scale_color_viridis(discrete = TRUE) +
  scale_size(range = c(2, 12)) +
  labs(y = "Meritvärde", x = "Kostnad")


```

 
